name: "CTM Energy Management System"
description: "Energy Management System with Tibber API integration"
version: "1.0.9"
slug: "ctm_ems"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8080/tcp: 8080
options:
  POSTGRES_HOST: ""
  POSTGRES_PORT: ""
  POSTGRES_DB: ""
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
  tibber_api_key: ""
  tibber_api_url: "https://api.tibber.com/v1-beta/gql"
schema:
  POSTGRES_HOST: str
  POSTGRES_PORT: int
  POSTGRES_USER: str
  POSTGRES_DB: str
  POSTGRES_PASSWORD: str
  tibber_api_key: str
  tibber_api_url: str
environment:
  NODE_ENV: "production"
