name: "CTM Energy Management System"
description: "Energy Management System with Tibber API integration"
version: "1.0.0"
slug: "ctm_ems"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8080/tcp: 8080
options:
  tibber_api_key: ""
  tibber_api_url: "https://api.tibber.com/v1-beta/gql"
schema:
  tibber_api_key: str
  tibber_api_url: str
environment:
  NODE_ENV: "production"
